apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask
  name: flask
spec:
  type: LoadBalancer
  selector:
    app: k8s
  ports:
    - port: 8080
      targetPort: 5000
---      
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask
  name: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: hooong2/project:47
        ports:
          - containerPort: 5000
